import type { Metadata } from "next";
import "./globals.css";
import "../styles/main.scss";
import Header from "../components/shared/Header";
import Footer from "../components/shared/Footer";

export const metadata: Metadata = {
  title: "Om Namah Shivay",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
